### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brylie** [colab-coop/bylaws#15]
Under what license are these bylaws shared? What are the permissions and/or restrictions for anyone wanting to reuse, modify, and share these bylaws?

**Comment by brodavi** [comment]
@brylie to my knowledge, bylaws do not have any copyright protection. But if I am mistaken in that, then let me declare these bylaws to be in the public domain, free to reuse, modify, and share at will :) In fact, these bylaws themselves were, if I am not mistaken, inspired heavily by: http://institute.coop/resources/sample-worker-cooperative-bylaws
